language: python
sudo: false
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install tox-travis
script:
- tox
deploy:
  provider: pypi
  user: dangle
  password:
    secure: N+iuk3Vn4zKWrDeK5ln7BKrs9EbSfoAqGc+zbeaEHcWn+wNXmdp9poNdy14pIKzrPXBfZiEy7MLDBzmGwvi9BkEivEV21tS8FJ45p/Rm/1HhNc1LygfiIeaO1NivYluzIOsczutKXOoDqvGtqc2UYPOuvd7ybosLpjMPGG6bLd8gAHMCaBuI5nl17alB8igdrhXBMbpBiir/7tKlaYfZvO43Ix3UULExkdQHdZBLpSFdgG11Fv9cq8jyrLZtdmXzae0Yu0og+OPl1AGUtR6I4piBShYzN29s6AXQv+FcdORGtfIKzbPGjDlYed5URp0Q00m7mojeqnCawqzWxMhl2wKGvkI+f4ybRhjHTAb70DzJbvjOiSC6lwbvOFs3mp65iR5lEXtJ4+5dM70TSrk8hGGRhHKYf/ZuNFgr8EdaHna8SVTex67EB7dbb0b4oyzeDVCRFYaSCxEh7h3xnlyv3BwJ4TdZ6wshOn2KNf/Ritr3LOXjwJ9VCsahJ3EIoV7YEzsLcLCgpt4RVToEuHdGmEmSSFwxYfVfD0CPvHwHrTPunq/gtfFwtKum4gpgvgWcUQYH+LoHXjjco4bVZL3p9qsbee22tfAF2Ke9ldvO3MMKuJE4/3LA2/iWLH1Xj+rsDS6FqGQ9GLmejvXaZW47xUPyxVR1Sv49pVgnQJJIyWo=
  on:
    tags: true
    repo: containenv/rapcom
